<?php
return array (
  'app' => 'Admin',
  'model' => 'Operate',
  'action' => 'default',
  'data' => '',
  'type' => '1',
  'status' => '1',
  'is_cp' => '0',
  'name' => '运营中心',
  'icon' => 'th',
  'remark' => '',
  'listorder' => '0',
  'children' => 
  array (
    array (
      'app' => 'Admin',
      'model' => 'Game',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'is_cp' => '0',
      'name' => '游戏管理',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Admin',
      'model' => 'Gift',
      'action' => 'giftList',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'is_cp' => '0',
      'name' => '礼包管理',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Admin',
      'model' => 'Payway',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'is_cp' => '0',
      'name' => '支付管理',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Admin',
      'model' => 'Subpackage',
      'action' => 'qudaoindex',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'is_cp' => '0',
      'name' => '一键分包',
      'icon' => '',
      'remark' => '',
      'listorder' => '3',
      'children' => 
      array (
        array (
          'app' => 'Admin',
          'model' => 'Subpackage',
          'action' => 'subpackage',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'is_cp' => '0',
          'name' => '分包函数',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Admin',
          'model' => 'Subpackage',
          'action' => 'updatepackage',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'is_cp' => '0',
          'name' => '更新函数',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Admin',
          'model' => 'Subpackage',
          'action' => 'addagent',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'is_cp' => '0',
          'name' => '添加渠道',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Admin',
          'model' => 'Subpackage',
          'action' => 'addagent_post',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'is_cp' => '0',
          'name' => '渠道添加请求函数',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
      ),
    ),
    array (
      'app' => 'Admin',
      'model' => 'Member',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'is_cp' => '0',
      'name' => '玩家管理',
      'icon' => '',
      'remark' => '',
      'listorder' => '4',
    ),
    array (
      'app' => 'Admin',
      'model' => 'Agent',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'is_cp' => '0',
      'name' => '渠道管理',
      'icon' => '',
      'remark' => '',
      'listorder' => '5',
      'children' => 
      array (
        array (
          'app' => 'Admin',
          'model' => 'Agent',
          'action' => 'addagent',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'is_cp' => '0',
          'name' => '渠道管理-添加渠道',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Admin',
          'model' => 'Agent',
          'action' => 'addagent_post',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'is_cp' => '0',
          'name' => '渠道管理-添加渠道提交函数',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Admin',
          'model' => 'Agent',
          'action' => 'ban',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'is_cp' => '0',
          'name' => '渠道管理-拉黑成员',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Admin',
          'model' => 'Agent',
          'action' => 'cancelban',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'is_cp' => '0',
          'name' => '渠道管理-取消拉黑成员',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Admin',
          'model' => 'Agent',
          'action' => 'edit',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'is_cp' => '0',
          'name' => '渠道管理-编辑成员',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Admin',
          'model' => 'Agent',
          'action' => 'edit_post',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'is_cp' => '0',
          'name' => '渠道管理-编辑成员提交函数',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
      ),
    ),
  ),
);