<?php
return array (
  'app' => 'Admin',
  'model' => 'Setting',
  'action' => 'default',
  'data' => '',
  'type' => '1',
  'status' => '1',
  'is_cp' => '0',
  'name' => '设置',
  'icon' => 'cogs',
  'remark' => '',
  'listorder' => '2',
  'children' => 
  array (
    array (
      'app' => 'Admin',
      'model' => 'Setting',
      'action' => 'password',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'is_cp' => '0',
      'name' => '修改密码',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
      'children' => 
      array (
        array (
          'app' => 'Admin',
          'model' => 'Setting',
          'action' => 'password_post',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'is_cp' => '0',
          'name' => '修改密码函数',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Admin',
          'model' => 'User',
          'action' => 'userinfo',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'is_cp' => '0',
          'name' => '用户信息',
          'icon' => '',
          'remark' => '用户信息',
          'listorder' => '0',
        ),
        array (
          'app' => 'Admin',
          'model' => 'User',
          'action' => 'userinfo_post',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'is_cp' => '0',
          'name' => '用户信息修改',
          'icon' => '',
          'remark' => '修改用户信息',
          'listorder' => '0',
        ),
      ),
    ),
    array (
      'app' => 'Admin',
      'model' => 'Mailer',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'is_cp' => '0',
      'name' => '邮箱配置',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Admin',
      'model' => 'User',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'is_cp' => '0',
      'name' => '管理员',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
      'children' => 
      array (
        array (
          'app' => 'Admin',
          'model' => 'User',
          'action' => 'ban',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'is_cp' => '0',
          'name' => '禁用管理员',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Admin',
          'model' => 'User',
          'action' => 'cancelban',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'is_cp' => '0',
          'name' => '启用管理员',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Admin',
          'model' => 'User',
          'action' => 'edit',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'is_cp' => '0',
          'name' => '管理员编辑',
          'icon' => '',
          'remark' => '',
          'listorder' => '1000',
          'children' => 
          array (
            array (
              'app' => 'Admin',
              'model' => 'User',
              'action' => 'edit_post',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'is_cp' => '0',
              'name' => '编辑提交',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
        array (
          'app' => 'Admin',
          'model' => 'User',
          'action' => 'add',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'is_cp' => '0',
          'name' => '管理员添加',
          'icon' => '',
          'remark' => '',
          'listorder' => '1000',
          'children' => 
          array (
            array (
              'app' => 'Admin',
              'model' => 'User',
              'action' => 'add_post',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'is_cp' => '0',
              'name' => '添加提交',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
      ),
    ),
    array (
      'app' => 'Admin',
      'model' => 'Contact',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'is_cp' => '0',
      'name' => '客服管理',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
      'children' => 
      array (
        array (
          'app' => 'Admin',
          'model' => 'Contact',
          'action' => 'editContact',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'is_cp' => '0',
          'name' => '修改客服信息',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
      ),
    ),
    array (
      'app' => 'Admin',
      'model' => 'Rbac',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'is_cp' => '0',
      'name' => '角色管理',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
      'children' => 
      array (
        array (
          'app' => 'Admin',
          'model' => 'User',
          'action' => 'delete',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'is_cp' => '0',
          'name' => '删除管理员',
          'icon' => '',
          'remark' => '',
          'listorder' => '1000',
        ),
        array (
          'app' => 'Admin',
          'model' => 'Rbac',
          'action' => 'member',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'is_cp' => '0',
          'name' => '成员管理',
          'icon' => '',
          'remark' => '',
          'listorder' => '1000',
        ),
        array (
          'app' => 'Admin',
          'model' => 'Rbac',
          'action' => 'authorize',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'is_cp' => '0',
          'name' => '权限设置',
          'icon' => '',
          'remark' => '',
          'listorder' => '1000',
          'children' => 
          array (
            array (
              'app' => 'Admin',
              'model' => 'Rbac',
              'action' => 'authorize_post',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'is_cp' => '0',
              'name' => '提交设置',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
        array (
          'app' => 'Admin',
          'model' => 'Rbac',
          'action' => 'roleedit',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'is_cp' => '0',
          'name' => '编辑角色',
          'icon' => '',
          'remark' => '',
          'listorder' => '1000',
          'children' => 
          array (
            array (
              'app' => 'Admin',
              'model' => 'Rbac',
              'action' => 'roleedit_post',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'is_cp' => '0',
              'name' => '提交编辑',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
        array (
          'app' => 'Admin',
          'model' => 'Rbac',
          'action' => 'roledelete',
          'data' => '',
          'type' => '1',
          'status' => '1',
          'is_cp' => '0',
          'name' => '删除角色',
          'icon' => '',
          'remark' => '',
          'listorder' => '1000',
        ),
        array (
          'app' => 'Admin',
          'model' => 'Rbac',
          'action' => 'roleadd',
          'data' => '',
          'type' => '1',
          'status' => '1',
          'is_cp' => '0',
          'name' => '添加角色',
          'icon' => '',
          'remark' => '',
          'listorder' => '1000',
          'children' => 
          array (
            array (
              'app' => 'Admin',
              'model' => 'Rbac',
              'action' => 'roleadd_post',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'is_cp' => '0',
              'name' => '提交添加',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
      ),
    ),
    array (
      'app' => 'Admin',
      'model' => 'Menu',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'is_cp' => '0',
      'name' => '菜单管理',
      'icon' => 'list',
      'remark' => '',
      'listorder' => '20',
    ),
  ),
);