<?php
return array (
  'app' => 'Admin',
  'model' => 'Data',
  'action' => 'default',
  'data' => '',
  'type' => '1',
  'status' => '1',
  'is_cp' => '0',
  'name' => '数据中心',
  'icon' => 'database',
  'remark' => '',
  'listorder' => '1',
  'children' => 
  array (
    array (
      'app' => 'Admin',
      'model' => 'Pay',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'is_cp' => '0',
      'name' => '充值数据',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Admin',
      'model' => 'Member',
      'action' => 'dataindex',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'is_cp' => '0',
      'name' => '玩家数据',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Admin',
      'model' => 'Pay',
      'action' => 'orderindex',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'is_cp' => '0',
      'name' => '订单数据',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Admin',
      'model' => 'Agent',
      'action' => 'dataindex',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'is_cp' => '0',
      'name' => '渠道数据',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Admin',
      'model' => 'Pay',
      'action' => 'gameindex',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'is_cp' => '0',
      'name' => '游戏数据',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Admin',
      'model' => 'Flow',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'is_cp' => '0',
      'name' => '流量统计',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
      'children' => 
      array (
        array (
          'app' => 'Admin',
          'model' => 'Flow',
          'action' => 'monthindex',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'is_cp' => '0',
          'name' => '月度流量',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
      ),
    ),
  ),
);